import type { AITypeDef } from "./types.js";

export const AI_TYPES: Record<string, AITypeDef> = {
  scavenger_grunt: {
    id: "scavenger_grunt",
    name: "Scavenger Grunt",
    health: 70,
    armor: 0,
    speed: 3.0,
    weaponId: "rust_pistol",
    detectionRadius: 25,
    attackRange: 25,
    fireRate: 1.2,
    burstSize: 1,
    accuracy: 0.45,
    behavior: "grunt",
    lootTableId: "ai_scavenger_grunt",
    xpValue: 10,
  },
  scavenger_rifleman: {
    id: "scavenger_rifleman",
    name: "Scavenger Rifleman",
    health: 90,
    armor: 10,
    speed: 3.2,
    weaponId: "scrap_rifle",
    detectionRadius: 35,
    attackRange: 45,
    fireRate: 0.35,
    burstSize: 3,
    accuracy: 0.55,
    behavior: "rifleman",
    lootTableId: "ai_scavenger_rifleman",
    xpValue: 15,
  },
  armored_captain: {
    id: "armored_captain",
    name: "Armored Captain",
    health: 250,
    armor: 50,
    speed: 2.6,
    weaponId: "pump_shotgun",
    detectionRadius: 30,
    attackRange: 18,
    fireRate: 1.0,
    burstSize: 1,
    accuracy: 0.6,
    behavior: "captain",
    lootTableId: "ai_armored_captain",
    xpValue: 50,
  },
  scout_drone: {
    id: "scout_drone",
    name: "Scout Drone",
    health: 50,
    armor: 0,
    speed: 4.5,
    weaponId: "rust_pistol",
    detectionRadius: 40,
    attackRange: 25,
    fireRate: 0.5,
    burstSize: 2,
    accuracy: 0.4,
    behavior: "drone",
    lootTableId: "ai_drone",
    xpValue: 12,
    flying: true,
  },
  sentry_turret: {
    id: "sentry_turret",
    name: "Sentry Turret",
    health: 120,
    armor: 30,
    speed: 0,
    weaponId: "compact_smg",
    detectionRadius: 35,
    attackRange: 35,
    fireRate: 0.2,
    burstSize: 5,
    accuracy: 0.65,
    behavior: "turret",
    lootTableId: "ai_turret",
    xpValue: 20,
  },
  heavy_machine: {
    id: "heavy_machine",
    name: "Heavy Machine Unit",
    health: 500,
    armor: 100,
    speed: 1.8,
    weaponId: "marksman_rifle",
    detectionRadius: 50,
    attackRange: 60,
    fireRate: 0.6,
    burstSize: 1,
    accuracy: 0.75,
    behavior: "heavy",
    lootTableId: "ai_heavy_machine",
    xpValue: 100,
  },
};

export function getAIType(id: string): AITypeDef | undefined {
  return AI_TYPES[id];
}
