import type { ItemDef, ArmorDef } from "./types.js";

export const ITEMS: Record<string, ItemDef> = {
  // Currency
  scrap: {
    id: "scrap",
    name: "Scrap",
    description: "Common salvage currency.",
    category: "currency",
    rarity: "common",
    stackable: true,
    maxStack: 9999,
    slotWeight: 0,
  },

  // Common resources
  wood: {
    id: "wood",
    name: "Wood",
    description: "Salvaged timber.",
    category: "resource",
    rarity: "common",
    stackable: true,
    maxStack: 99,
    slotWeight: 1,
  },
  cloth: {
    id: "cloth",
    name: "Cloth",
    description: "Worn fabric for repairs and armor.",
    category: "resource",
    rarity: "common",
    stackable: true,
    maxStack: 99,
    slotWeight: 1,
  },
  iron_shards: {
    id: "iron_shards",
    name: "Iron Shards",
    description: "Small pieces of scrap metal.",
    category: "resource",
    rarity: "common",
    stackable: true,
    maxStack: 99,
    slotWeight: 1,
  },
  rope: {
    id: "rope",
    name: "Rope",
    description: "Sturdy salvaged line.",
    category: "resource",
    rarity: "common",
    stackable: true,
    maxStack: 99,
    slotWeight: 1,
  },
  gunpowder: {
    id: "gunpowder",
    name: "Gunpowder",
    description: "Volatile powder for ammunition.",
    category: "resource",
    rarity: "uncommon",
    stackable: true,
    maxStack: 99,
    slotWeight: 1,
  },
  oil: {
    id: "oil",
    name: "Oil",
    description: "Machine oil for repairs.",
    category: "resource",
    rarity: "common",
    stackable: true,
    maxStack: 99,
    slotWeight: 1,
  },

  // Weapon components
  barrel: {
    id: "barrel",
    name: "Barrel",
    description: "Standard weapon barrel.",
    category: "component",
    rarity: "common",
    stackable: true,
    maxStack: 20,
    slotWeight: 1,
  },
  long_barrel: {
    id: "long_barrel",
    name: "Long Barrel",
    description: "Rifle-length precision barrel.",
    category: "component",
    rarity: "uncommon",
    stackable: true,
    maxStack: 20,
    slotWeight: 1,
  },
  receiver: {
    id: "receiver",
    name: "Receiver",
    description: "Weapon receiver assembly.",
    category: "component",
    rarity: "common",
    stackable: true,
    maxStack: 20,
    slotWeight: 1,
  },
  stock: {
    id: "stock",
    name: "Stock",
    description: "Shoulder stock.",
    category: "component",
    rarity: "common",
    stackable: true,
    maxStack: 20,
    slotWeight: 1,
  },
  magazine: {
    id: "magazine",
    name: "Magazine",
    description: "Standard box magazine.",
    category: "component",
    rarity: "common",
    stackable: true,
    maxStack: 20,
    slotWeight: 1,
  },
  spring: {
    id: "spring",
    name: "Spring",
    description: "Recoil spring.",
    category: "component",
    rarity: "common",
    stackable: true,
    maxStack: 50,
    slotWeight: 1,
  },
  grip: {
    id: "grip",
    name: "Grip",
    description: "Pistol grip.",
    category: "component",
    rarity: "common",
    stackable: true,
    maxStack: 20,
    slotWeight: 1,
  },
  optic_lens: {
    id: "optic_lens",
    name: "Optic Lens",
    description: "Glass lens for scopes.",
    category: "component",
    rarity: "uncommon",
    stackable: true,
    maxStack: 20,
    slotWeight: 1,
  },
  suppressor_baffle: {
    id: "suppressor_baffle",
    name: "Suppressor Baffle",
    description: "Sound-dampening baffles.",
    category: "component",
    rarity: "rare",
    stackable: true,
    maxStack: 10,
    slotWeight: 1,
  },

  // Rare resources
  rare_alloy: {
    id: "rare_alloy",
    name: "Rare Alloy",
    description: "High-grade alloy from military gear.",
    category: "resource",
    rarity: "rare",
    stackable: true,
    maxStack: 20,
    slotWeight: 1,
  },
  machine_core: {
    id: "machine_core",
    name: "Machine Core",
    description: "Intact power core from a machine unit.",
    category: "resource",
    rarity: "rare",
    stackable: true,
    maxStack: 10,
    slotWeight: 2,
  },
  storm_crystal: {
    id: "storm_crystal",
    name: "Storm Crystal",
    description: "Crystal charged by storm energy.",
    category: "resource",
    rarity: "epic",
    stackable: true,
    maxStack: 5,
    slotWeight: 2,
  },
  military_circuit: {
    id: "military_circuit",
    name: "Military Circuit",
    description: "Encrypted military electronics.",
    category: "resource",
    rarity: "rare",
    stackable: true,
    maxStack: 10,
    slotWeight: 1,
  },
  reinforced_plate: {
    id: "reinforced_plate",
    name: "Reinforced Plate",
    description: "Armor plate.",
    category: "resource",
    rarity: "uncommon",
    stackable: true,
    maxStack: 20,
    slotWeight: 2,
  },

  // Consumables
  light_ammo: {
    id: "light_ammo",
    name: "Light Ammo",
    description: "Pistol and SMG rounds.",
    category: "consumable",
    rarity: "common",
    stackable: true,
    maxStack: 120,
    slotWeight: 0.5,
  },
  rifle_ammo: {
    id: "rifle_ammo",
    name: "Rifle Ammo",
    description: "Rifle and marksman rounds.",
    category: "consumable",
    rarity: "common",
    stackable: true,
    maxStack: 90,
    slotWeight: 0.5,
  },
  shells: {
    id: "shells",
    name: "Shells",
    description: "Shotgun shells.",
    category: "consumable",
    rarity: "common",
    stackable: true,
    maxStack: 40,
    slotWeight: 0.5,
  },
  med_kit: {
    id: "med_kit",
    name: "Med Kit",
    description: "Restores 60 health over 6 seconds.",
    category: "consumable",
    rarity: "uncommon",
    stackable: true,
    maxStack: 5,
    slotWeight: 1,
  },
  bandage: {
    id: "bandage",
    name: "Bandage",
    description: "Restores 25 health over 5 seconds.",
    category: "consumable",
    rarity: "common",
    stackable: true,
    maxStack: 10,
    slotWeight: 0.5,
  },
  boat_repair_kit: {
    id: "boat_repair_kit",
    name: "Boat Repair Kit",
    description: "Repairs boat hull damage.",
    category: "consumable",
    rarity: "uncommon",
    stackable: true,
    maxStack: 5,
    slotWeight: 2,
  },
  frag_grenade: {
    id: "frag_grenade",
    name: "Frag Grenade",
    description: "Explosive thrown weapon.",
    category: "consumable",
    rarity: "uncommon",
    stackable: true,
    maxStack: 3,
    slotWeight: 1,
  },

  // Weapons
  rust_pistol: {
    id: "rust_pistol",
    name: "Rust Pistol",
    description: "Reliable scrap-built pistol.",
    category: "weapon",
    rarity: "common",
    stackable: false,
    maxStack: 1,
    slotWeight: 2,
  },
  compact_smg: {
    id: "compact_smg",
    name: "Compact SMG",
    description: "Fast-firing close-range weapon.",
    category: "weapon",
    rarity: "uncommon",
    stackable: false,
    maxStack: 1,
    slotWeight: 3,
  },
  pump_shotgun: {
    id: "pump_shotgun",
    name: "Pump Shotgun",
    description: "Devastating at close range.",
    category: "weapon",
    rarity: "uncommon",
    stackable: false,
    maxStack: 1,
    slotWeight: 3,
  },
  scrap_rifle: {
    id: "scrap_rifle",
    name: "Scrap Rifle",
    description: "Versatile assault rifle.",
    category: "weapon",
    rarity: "rare",
    stackable: false,
    maxStack: 1,
    slotWeight: 3,
  },
  burst_carbine: {
    id: "burst_carbine",
    name: "Burst Carbine",
    description: "Three-round burst carbine.",
    category: "weapon",
    rarity: "rare",
    stackable: false,
    maxStack: 1,
    slotWeight: 3,
  },
  marksman_rifle: {
    id: "marksman_rifle",
    name: "Marksman Rifle",
    description: "Semi-automatic precision rifle.",
    category: "weapon",
    rarity: "rare",
    stackable: false,
    maxStack: 1,
    slotWeight: 4,
  },
  bolt_rifle: {
    id: "bolt_rifle",
    name: "Bolt Rifle",
    description: "High-power bolt-action sniper.",
    category: "weapon",
    rarity: "epic",
    stackable: false,
    maxStack: 1,
    slotWeight: 4,
  },

  // Attachments
  short_barrel: {
    id: "short_barrel",
    name: "Short Barrel",
    description: "Improves handling, worsens recoil.",
    category: "attachment",
    rarity: "common",
    stackable: true,
    maxStack: 5,
    slotWeight: 1,
  },
  heavy_barrel: {
    id: "heavy_barrel",
    name: "Heavy Barrel",
    description: "Improves accuracy, slows handling.",
    category: "attachment",
    rarity: "uncommon",
    stackable: true,
    maxStack: 5,
    slotWeight: 1,
  },
  suppressor: {
    id: "suppressor",
    name: "Suppressor",
    description: "Quieter shots with slight damage falloff.",
    category: "attachment",
    rarity: "rare",
    stackable: true,
    maxStack: 5,
    slotWeight: 1,
  },
  extended_mag: {
    id: "extended_mag",
    name: "Extended Magazine",
    description: "Larger magazine, slower reload.",
    category: "attachment",
    rarity: "uncommon",
    stackable: true,
    maxStack: 5,
    slotWeight: 1,
  },
  vertical_grip: {
    id: "vertical_grip",
    name: "Vertical Grip",
    description: "Reduces horizontal recoil.",
    category: "attachment",
    rarity: "common",
    stackable: true,
    maxStack: 5,
    slotWeight: 1,
  },
  red_dot: {
    id: "red_dot",
    name: "Red Dot Sight",
    description: "Light optic.",
    category: "attachment",
    rarity: "common",
    stackable: true,
    maxStack: 5,
    slotWeight: 1,
  },

  // Armor
  basic_armor: {
    id: "basic_armor",
    name: "Basic Armor",
    description: "Scrap plate armor. +25 armor.",
    category: "armor",
    rarity: "common",
    stackable: false,
    maxStack: 1,
    slotWeight: 3,
  },
  medium_armor: {
    id: "medium_armor",
    name: "Medium Armor",
    description: "Reinforced armor. +50 armor.",
    category: "armor",
    rarity: "uncommon",
    stackable: false,
    maxStack: 1,
    slotWeight: 4,
  },

  // Contracts
  weapons_crate: {
    id: "weapons_crate",
    name: "Weapons Crate",
    description: "Sealed weapons crate for delivery.",
    category: "contract",
    rarity: "rare",
    stackable: false,
    maxStack: 1,
    slotWeight: 3,
  },
  vault_key: {
    id: "vault_key",
    name: "Vault Key",
    description: "Key to a locked vault.",
    category: "contract",
    rarity: "rare",
    stackable: false,
    maxStack: 1,
    slotWeight: 0,
  },
  signal_core: {
    id: "signal_core",
    name: "Signal Core",
    description: "Encrypted signal device.",
    category: "contract",
    rarity: "epic",
    stackable: false,
    maxStack: 1,
    slotWeight: 2,
  },
  contraband_package: {
    id: "contraband_package",
    name: "Contraband Package",
    description: "High-value stolen cargo.",
    category: "contract",
    rarity: "epic",
    stackable: false,
    maxStack: 1,
    slotWeight: 3,
  },

  // Blueprints
  smg_blueprint: {
    id: "smg_blueprint",
    name: "SMG Blueprint",
    description: "Unlocks Compact SMG crafting.",
    category: "blueprint",
    rarity: "uncommon",
    stackable: true,
    maxStack: 1,
    slotWeight: 0,
  },
  scrap_rifle_blueprint: {
    id: "scrap_rifle_blueprint",
    name: "Scrap Rifle Blueprint",
    description: "Unlocks Scrap Rifle crafting.",
    category: "blueprint",
    rarity: "rare",
    stackable: true,
    maxStack: 1,
    slotWeight: 0,
  },
  marksman_blueprint: {
    id: "marksman_blueprint",
    name: "Marksman Blueprint",
    description: "Unlocks Marksman Rifle crafting.",
    category: "blueprint",
    rarity: "rare",
    stackable: true,
    maxStack: 1,
    slotWeight: 0,
  },
  suppressor_blueprint: {
    id: "suppressor_blueprint",
    name: "Suppressor Blueprint",
    description: "Unlocks Suppressor crafting.",
    category: "blueprint",
    rarity: "rare",
    stackable: true,
    maxStack: 1,
    slotWeight: 0,
  },
};

export const ARMOR: Record<string, ArmorDef> = {
  basic_armor: { id: "basic_armor", itemId: "basic_armor", name: "Basic Armor", armor: 25, slot: "armor" },
  medium_armor: { id: "medium_armor", itemId: "medium_armor", name: "Medium Armor", armor: 50, slot: "armor" },
};

export function getItem(id: string): ItemDef | undefined {
  return ITEMS[id];
}
