import type { LootTableDef } from "./types.js";

export const LOOT_TABLES: Record<string, LootTableDef> = {
  driftwood_common: {
    id: "driftwood_common",
    entries: [
      { itemId: "scrap", countMin: 3, countMax: 8, weight: 40 },
      { itemId: "wood", countMin: 1, countMax: 3, weight: 30 },
      { itemId: "cloth", countMin: 1, countMax: 2, weight: 25 },
      { itemId: "rope", countMin: 1, countMax: 2, weight: 20 },
      { itemId: "light_ammo", countMin: 6, countMax: 18, weight: 20 },
      { itemId: "bandage", countMin: 1, countMax: 2, weight: 15 },
      { itemId: "iron_shards", countMin: 1, countMax: 3, weight: 15 },
      { itemId: "barrel", countMin: 1, countMax: 1, weight: 8 },
      { itemId: "receiver", countMin: 1, countMax: 1, weight: 6 },
    ],
    rollsMin: 1,
    rollsMax: 3,
  },
  fort_common: {
    id: "fort_common",
    entries: [
      { itemId: "scrap", countMin: 5, countMax: 12, weight: 35 },
      { itemId: "iron_shards", countMin: 2, countMax: 5, weight: 25 },
      { itemId: "gunpowder", countMin: 1, countMax: 3, weight: 20 },
      { itemId: "rifle_ammo", countMin: 10, countMax: 25, weight: 20 },
      { itemId: "shells", countMin: 4, countMax: 10, weight: 15 },
      { itemId: "barrel", countMin: 1, countMax: 2, weight: 15 },
      { itemId: "receiver", countMin: 1, countMax: 2, weight: 12 },
      { itemId: "spring", countMin: 1, countMax: 3, weight: 12 },
      { itemId: "stock", countMin: 1, countMax: 1, weight: 10 },
      { itemId: "magazine", countMin: 1, countMax: 1, weight: 10 },
      { itemId: "reinforced_plate", countMin: 1, countMax: 1, weight: 8 },
      { itemId: "med_kit", countMin: 1, countMax: 1, weight: 8 },
    ],
    rollsMin: 2,
    rollsMax: 4,
  },
  fort_vault: {
    id: "fort_vault",
    entries: [
      { itemId: "scrap", countMin: 20, countMax: 50, weight: 30 },
      { itemId: "rifle_ammo", countMin: 30, countMax: 60, weight: 25 },
      { itemId: "barrel", countMin: 2, countMax: 4, weight: 20 },
      { itemId: "receiver", countMin: 2, countMax: 4, weight: 18 },
      { itemId: "long_barrel", countMin: 1, countMax: 1, weight: 15 },
      { itemId: "optic_lens", countMin: 1, countMax: 1, weight: 12 },
      { itemId: "rare_alloy", countMin: 1, countMax: 2, weight: 10 },
      { itemId: "weapons_crate", countMin: 1, countMax: 1, weight: 8 },
      { itemId: "smg_blueprint", countMin: 1, countMax: 1, weight: 5 },
      { itemId: "scrap_rifle_blueprint", countMin: 1, countMax: 1, weight: 3 },
    ],
    rollsMin: 3,
    rollsMax: 5,
  },
  shipyard_common: {
    id: "shipyard_common",
    entries: [
      { itemId: "scrap", countMin: 6, countMax: 15, weight: 30 },
      { itemId: "iron_shards", countMin: 2, countMax: 6, weight: 25 },
      { itemId: "oil", countMin: 1, countMax: 3, weight: 25 },
      { itemId: "spring", countMin: 1, countMax: 4, weight: 20 },
      { itemId: "receiver", countMin: 1, countMax: 2, weight: 18 },
      { itemId: "magazine", countMin: 1, countMax: 2, weight: 15 },
      { itemId: "grip", countMin: 1, countMax: 1, weight: 12 },
      { itemId: "military_circuit", countMin: 1, countMax: 1, weight: 10 },
      { itemId: "rare_alloy", countMin: 1, countMax: 1, weight: 8 },
    ],
    rollsMin: 2,
    rollsMax: 4,
  },
  shipyard_machine: {
    id: "shipyard_machine",
    entries: [
      { itemId: "machine_core", countMin: 1, countMax: 1, weight: 20 },
      { itemId: "military_circuit", countMin: 1, countMax: 2, weight: 25 },
      { itemId: "rare_alloy", countMin: 1, countMax: 3, weight: 20 },
      { itemId: "scrap", countMin: 10, countMax: 30, weight: 20 },
      { itemId: "gunpowder", countMin: 2, countMax: 5, weight: 15 },
      { itemId: "marksman_blueprint", countMin: 1, countMax: 1, weight: 5 },
    ],
    rollsMin: 2,
    rollsMax: 4,
  },
  crown_common: {
    id: "crown_common",
    entries: [
      { itemId: "scrap", countMin: 10, countMax: 25, weight: 25 },
      { itemId: "rifle_ammo", countMin: 20, countMax: 50, weight: 25 },
      { itemId: "military_circuit", countMin: 1, countMax: 3, weight: 20 },
      { itemId: "reinforced_plate", countMin: 1, countMax: 2, weight: 18 },
      { itemId: "rare_alloy", countMin: 1, countMax: 2, weight: 15 },
      { itemId: "long_barrel", countMin: 1, countMax: 1, weight: 12 },
      { itemId: "optic_lens", countMin: 1, countMax: 1, weight: 10 },
      { itemId: "suppressor_baffle", countMin: 1, countMax: 1, weight: 8 },
      { itemId: "med_kit", countMin: 1, countMax: 2, weight: 10 },
    ],
    rollsMin: 3,
    rollsMax: 5,
  },
  crown_vault: {
    id: "crown_vault",
    entries: [
      { itemId: "scrap", countMin: 40, countMax: 100, weight: 20 },
      { itemId: "rare_alloy", countMin: 2, countMax: 5, weight: 20 },
      { itemId: "military_circuit", countMin: 2, countMax: 4, weight: 18 },
      { itemId: "long_barrel", countMin: 1, countMax: 2, weight: 15 },
      { itemId: "optic_lens", countMin: 1, countMax: 2, weight: 15 },
      { itemId: "suppressor_baffle", countMin: 1, countMax: 2, weight: 12 },
      { itemId: "signal_core", countMin: 1, countMax: 1, weight: 10 },
      { itemId: "suppressor_blueprint", countMin: 1, countMax: 1, weight: 6 },
      { itemId: "storm_crystal", countMin: 1, countMax: 1, weight: 3 },
    ],
    rollsMin: 4,
    rollsMax: 6,
  },
  leviathan_cargo: {
    id: "leviathan_cargo",
    entries: [
      { itemId: "scrap", countMin: 15, countMax: 40, weight: 25 },
      { itemId: "contraband_package", countMin: 1, countMax: 1, weight: 20 },
      { itemId: "boat_repair_kit", countMin: 1, countMax: 2, weight: 18 },
      { itemId: "rope", countMin: 2, countMax: 5, weight: 15 },
      { itemId: "rare_alloy", countMin: 1, countMax: 2, weight: 12 },
      { itemId: "wood", countMin: 3, countMax: 8, weight: 12 },
      { itemId: "smg_blueprint", countMin: 1, countMax: 1, weight: 5 },
    ],
    rollsMin: 3,
    rollsMax: 5,
  },
  ai_scavenger_grunt: {
    id: "ai_scavenger_grunt",
    entries: [
      { itemId: "scrap", countMin: 2, countMax: 5, weight: 35 },
      { itemId: "light_ammo", countMin: 3, countMax: 9, weight: 20 },
      { itemId: "cloth", countMin: 1, countMax: 2, weight: 15 },
      { itemId: "bandage", countMin: 1, countMax: 1, weight: 10 },
      { itemId: "iron_shards", countMin: 1, countMax: 2, weight: 10 },
    ],
    rollsMin: 1,
    rollsMax: 2,
  },
  ai_scavenger_rifleman: {
    id: "ai_scavenger_rifleman",
    entries: [
      { itemId: "scrap", countMin: 3, countMax: 7, weight: 30 },
      { itemId: "rifle_ammo", countMin: 5, countMax: 15, weight: 25 },
      { itemId: "barrel", countMin: 1, countMax: 1, weight: 12 },
      { itemId: "receiver", countMin: 1, countMax: 1, weight: 10 },
      { itemId: "bandage", countMin: 1, countMax: 1, weight: 10 },
    ],
    rollsMin: 1,
    rollsMax: 3,
  },
  ai_armored_captain: {
    id: "ai_armored_captain",
    entries: [
      { itemId: "scrap", countMin: 15, countMax: 30, weight: 25 },
      { itemId: "reinforced_plate", countMin: 1, countMax: 2, weight: 20 },
      { itemId: "vault_key", countMin: 1, countMax: 1, weight: 30 },
      { itemId: "rare_alloy", countMin: 1, countMax: 2, weight: 15 },
      { itemId: "smg_blueprint", countMin: 1, countMax: 1, weight: 10 },
    ],
    rollsMin: 2,
    rollsMax: 4,
  },
  ai_drone: {
    id: "ai_drone",
    entries: [
      { itemId: "military_circuit", countMin: 1, countMax: 1, weight: 50 },
      { itemId: "scrap", countMin: 2, countMax: 5, weight: 25 },
      { itemId: "rare_alloy", countMin: 1, countMax: 1, weight: 10 },
    ],
    rollsMin: 1,
    rollsMax: 2,
  },
  ai_turret: {
    id: "ai_turret",
    entries: [
      { itemId: "military_circuit", countMin: 1, countMax: 2, weight: 40 },
      { itemId: "scrap", countMin: 5, countMax: 12, weight: 30 },
      { itemId: "rifle_ammo", countMin: 10, countMax: 25, weight: 20 },
      { itemId: "rare_alloy", countMin: 1, countMax: 1, weight: 10 },
    ],
    rollsMin: 1,
    rollsMax: 3,
  },
  ai_heavy_machine: {
    id: "ai_heavy_machine",
    entries: [
      { itemId: "machine_core", countMin: 1, countMax: 1, weight: 40 },
      { itemId: "rare_alloy", countMin: 2, countMax: 4, weight: 30 },
      { itemId: "military_circuit", countMin: 2, countMax: 4, weight: 20 },
      { itemId: "scrap", countMin: 30, countMax: 80, weight: 20 },
      { itemId: "scrap_rifle_blueprint", countMin: 1, countMax: 1, weight: 10 },
      { itemId: "marksman_blueprint", countMin: 1, countMax: 1, weight: 5 },
    ],
    rollsMin: 4,
    rollsMax: 6,
  },
  signal_cache: {
    id: "signal_cache",
    entries: [
      { itemId: "scrap", countMin: 20, countMax: 50, weight: 25 },
      { itemId: "rare_alloy", countMin: 1, countMax: 3, weight: 20 },
      { itemId: "military_circuit", countMin: 1, countMax: 3, weight: 18 },
      { itemId: "machine_core", countMin: 1, countMax: 1, weight: 15 },
      { itemId: "optic_lens", countMin: 1, countMax: 1, weight: 12 },
      { itemId: "smg_blueprint", countMin: 1, countMax: 1, weight: 6 },
      { itemId: "scrap_rifle_blueprint", countMin: 1, countMax: 1, weight: 4 },
    ],
    rollsMin: 3,
    rollsMax: 5,
  },
};

export function getLootTable(id: string): LootTableDef | undefined {
  return LOOT_TABLES[id];
}
