import type { RecipeDef } from "./types.js";

export const RECIPES: Record<string, RecipeDef> = {
  rust_pistol: {
    id: "rust_pistol",
    name: "Rust Pistol",
    outputItemId: "rust_pistol",
    outputCount: 1,
    ingredients: [
      { itemId: "scrap", count: 10 },
      { itemId: "barrel", count: 1 },
      { itemId: "receiver", count: 1 },
    ],
    craftTimeMs: 2000,
    category: "weapon",
  },
  compact_smg: {
    id: "compact_smg",
    name: "Compact SMG",
    outputItemId: "compact_smg",
    outputCount: 1,
    ingredients: [
      { itemId: "scrap", count: 35 },
      { itemId: "receiver", count: 2 },
      { itemId: "spring", count: 2 },
      { itemId: "magazine", count: 1 },
      { itemId: "grip", count: 1 },
    ],
    requiredBlueprint: "smg_blueprint",
    craftTimeMs: 4000,
    category: "weapon",
  },
  pump_shotgun: {
    id: "pump_shotgun",
    name: "Pump Shotgun",
    outputItemId: "pump_shotgun",
    outputCount: 1,
    ingredients: [
      { itemId: "scrap", count: 30 },
      { itemId: "barrel", count: 2 },
      { itemId: "wood", count: 4 },
      { itemId: "receiver", count: 1 },
      { itemId: "spring", count: 1 },
    ],
    craftTimeMs: 3500,
    category: "weapon",
  },
  scrap_rifle: {
    id: "scrap_rifle",
    name: "Scrap Rifle",
    outputItemId: "scrap_rifle",
    outputCount: 1,
    ingredients: [
      { itemId: "scrap", count: 50 },
      { itemId: "barrel", count: 2 },
      { itemId: "receiver", count: 2 },
      { itemId: "stock", count: 1 },
      { itemId: "magazine", count: 1 },
      { itemId: "spring", count: 2 },
    ],
    requiredBlueprint: "scrap_rifle_blueprint",
    craftTimeMs: 5000,
    category: "weapon",
  },
  marksman_rifle: {
    id: "marksman_rifle",
    name: "Marksman Rifle",
    outputItemId: "marksman_rifle",
    outputCount: 1,
    ingredients: [
      { itemId: "scrap", count: 70 },
      { itemId: "long_barrel", count: 1 },
      { itemId: "receiver", count: 2 },
      { itemId: "stock", count: 1 },
      { itemId: "optic_lens", count: 1 },
      { itemId: "rare_alloy", count: 2 },
    ],
    requiredBlueprint: "marksman_blueprint",
    craftTimeMs: 7000,
    category: "weapon",
  },
  suppressor: {
    id: "suppressor",
    name: "Suppressor",
    outputItemId: "suppressor",
    outputCount: 1,
    ingredients: [
      { itemId: "suppressor_baffle", count: 2 },
      { itemId: "rare_alloy", count: 1 },
      { itemId: "scrap", count: 25 },
    ],
    requiredBlueprint: "suppressor_blueprint",
    craftTimeMs: 3000,
    category: "attachment",
  },
  basic_armor: {
    id: "basic_armor",
    name: "Basic Armor",
    outputItemId: "basic_armor",
    outputCount: 1,
    ingredients: [
      { itemId: "cloth", count: 5 },
      { itemId: "reinforced_plate", count: 1 },
      { itemId: "scrap", count: 20 },
    ],
    craftTimeMs: 3000,
    category: "armor",
  },
  boat_repair_kit: {
    id: "boat_repair_kit",
    name: "Boat Repair Kit",
    outputItemId: "boat_repair_kit",
    outputCount: 1,
    ingredients: [
      { itemId: "wood", count: 3 },
      { itemId: "rope", count: 2 },
      { itemId: "oil", count: 1 },
      { itemId: "scrap", count: 5 },
    ],
    craftTimeMs: 2500,
    category: "utility",
  },
  med_kit: {
    id: "med_kit",
    name: "Med Kit",
    outputItemId: "med_kit",
    outputCount: 1,
    ingredients: [
      { itemId: "cloth", count: 3 },
      { itemId: "oil", count: 1 },
      { itemId: "scrap", count: 5 },
    ],
    craftTimeMs: 2500,
    category: "consumable",
  },
  bandage: {
    id: "bandage",
    name: "Bandage",
    outputItemId: "bandage",
    outputCount: 2,
    ingredients: [
      { itemId: "cloth", count: 1 },
    ],
    craftTimeMs: 1000,
    category: "consumable",
  },
  light_ammo: {
    id: "light_ammo",
    name: "Light Ammo",
    outputItemId: "light_ammo",
    outputCount: 30,
    ingredients: [
      { itemId: "iron_shards", count: 2 },
      { itemId: "gunpowder", count: 1 },
      { itemId: "scrap", count: 2 },
    ],
    craftTimeMs: 2000,
    category: "consumable",
  },
  rifle_ammo: {
    id: "rifle_ammo",
    name: "Rifle Ammo",
    outputItemId: "rifle_ammo",
    outputCount: 20,
    ingredients: [
      { itemId: "iron_shards", count: 3 },
      { itemId: "gunpowder", count: 2 },
      { itemId: "scrap", count: 3 },
    ],
    craftTimeMs: 2500,
    category: "consumable",
  },
  shells: {
    id: "shells",
    name: "Shells",
    outputItemId: "shells",
    outputCount: 8,
    ingredients: [
      { itemId: "iron_shards", count: 2 },
      { itemId: "gunpowder", count: 2 },
      { itemId: "scrap", count: 2 },
    ],
    craftTimeMs: 2000,
    category: "consumable",
  },
};

export function getRecipe(id: string): RecipeDef | undefined {
  return RECIPES[id];
}
