import type { WeaponDef, AttachmentDef } from "./types.js";

export const WEAPONS: Record<string, WeaponDef> = {
  rust_pistol: {
    id: "rust_pistol",
    itemId: "rust_pistol",
    name: "Rust Pistol",
    type: "pistol",
    damage: 28,
    fireMode: "semi",
    rpm: 300,
    reloadTime: 1.5,
    magazineSize: 12,
    ammoType: "light_ammo",
    spreadBase: 0.025,
    spreadMove: 0.04,
    spreadAds: 0.012,
    recoilVertical: 0.012,
    recoilHorizontal: 0.003,
    recoilRecovery: 0.9,
    damageFalloffStart: 20,
    damageFalloffEnd: 60,
    minDamage: 14,
    effectiveRange: 40,
    adsZoom: 1.1,
    audibleRadius: 120,
    attachmentSlots: ["barrel", "optic", "magazine"],
  },
  compact_smg: {
    id: "compact_smg",
    itemId: "compact_smg",
    name: "Compact SMG",
    type: "smg",
    damage: 18,
    fireMode: "auto",
    rpm: 750,
    reloadTime: 2.1,
    magazineSize: 30,
    ammoType: "light_ammo",
    spreadBase: 0.04,
    spreadMove: 0.08,
    spreadAds: 0.025,
    recoilVertical: 0.018,
    recoilHorizontal: 0.012,
    recoilRecovery: 0.85,
    damageFalloffStart: 15,
    damageFalloffEnd: 45,
    minDamage: 10,
    effectiveRange: 25,
    adsZoom: 1.15,
    audibleRadius: 140,
    attachmentSlots: ["barrel", "optic", "magazine", "grip"],
  },
  pump_shotgun: {
    id: "pump_shotgun",
    itemId: "pump_shotgun",
    name: "Pump Shotgun",
    type: "shotgun",
    damage: 12,
    pellets: 8,
    fireMode: "semi",
    rpm: 70,
    reloadTime: 0.6,
    magazineSize: 6,
    ammoType: "shells",
    spreadBase: 0.08,
    spreadMove: 0.12,
    spreadAds: 0.05,
    recoilVertical: 0.05,
    recoilHorizontal: 0.02,
    recoilRecovery: 0.7,
    damageFalloffStart: 8,
    damageFalloffEnd: 25,
    minDamage: 4,
    effectiveRange: 15,
    adsZoom: 1.05,
    audibleRadius: 160,
    attachmentSlots: ["barrel", "optic"],
  },
  scrap_rifle: {
    id: "scrap_rifle",
    itemId: "scrap_rifle",
    name: "Scrap Rifle",
    type: "rifle",
    damage: 34,
    fireMode: "auto",
    rpm: 600,
    reloadTime: 2.4,
    magazineSize: 30,
    ammoType: "rifle_ammo",
    spreadBase: 0.025,
    spreadMove: 0.06,
    spreadAds: 0.012,
    recoilVertical: 0.022,
    recoilHorizontal: 0.008,
    recoilRecovery: 0.88,
    damageFalloffStart: 30,
    damageFalloffEnd: 90,
    minDamage: 20,
    effectiveRange: 60,
    adsZoom: 1.25,
    audibleRadius: 180,
    attachmentSlots: ["barrel", "optic", "magazine", "grip", "stock"],
  },
  burst_carbine: {
    id: "burst_carbine",
    itemId: "burst_carbine",
    name: "Burst Carbine",
    type: "rifle",
    damage: 27,
    fireMode: "burst",
    burstCount: 3,
    rpm: 600,
    reloadTime: 2.2,
    magazineSize: 24,
    ammoType: "rifle_ammo",
    spreadBase: 0.02,
    spreadMove: 0.045,
    spreadAds: 0.008,
    recoilVertical: 0.02,
    recoilHorizontal: 0.006,
    recoilRecovery: 0.9,
    damageFalloffStart: 25,
    damageFalloffEnd: 75,
    minDamage: 16,
    effectiveRange: 55,
    adsZoom: 1.3,
    audibleRadius: 170,
    attachmentSlots: ["barrel", "optic", "magazine", "grip"],
  },
  marksman_rifle: {
    id: "marksman_rifle",
    itemId: "marksman_rifle",
    name: "Marksman Rifle",
    type: "marksman",
    damage: 55,
    fireMode: "semi",
    rpm: 240,
    reloadTime: 2.6,
    magazineSize: 10,
    ammoType: "rifle_ammo",
    spreadBase: 0.01,
    spreadMove: 0.05,
    spreadAds: 0.002,
    recoilVertical: 0.035,
    recoilHorizontal: 0.004,
    recoilRecovery: 0.82,
    damageFalloffStart: 50,
    damageFalloffEnd: 150,
    minDamage: 35,
    effectiveRange: 120,
    adsZoom: 2.5,
    audibleRadius: 200,
    attachmentSlots: ["barrel", "optic", "magazine", "stock"],
  },
  bolt_rifle: {
    id: "bolt_rifle",
    itemId: "bolt_rifle",
    name: "Bolt Rifle",
    type: "bolt",
    damage: 80,
    fireMode: "semi",
    rpm: 50,
    reloadTime: 3.0,
    magazineSize: 5,
    ammoType: "rifle_ammo",
    spreadBase: 0.005,
    spreadMove: 0.08,
    spreadAds: 0.0,
    recoilVertical: 0.06,
    recoilHorizontal: 0.005,
    recoilRecovery: 0.75,
    damageFalloffStart: 80,
    damageFalloffEnd: 250,
    minDamage: 60,
    effectiveRange: 200,
    adsZoom: 4.0,
    audibleRadius: 250,
    attachmentSlots: ["barrel", "optic", "magazine", "stock"],
  },
};

export const ATTACHMENTS: Record<string, AttachmentDef> = {
  short_barrel: {
    id: "short_barrel",
    itemId: "short_barrel",
    name: "Short Barrel",
    slot: "barrel",
    modifiers: { spreadBase: 0.012, recoilVertical: 0.008, damage: 0, spreadAds: 0.006 },
  },
  heavy_barrel: {
    id: "heavy_barrel",
    itemId: "heavy_barrel",
    name: "Heavy Barrel",
    slot: "barrel",
    modifiers: { spreadBase: -0.01, spreadMove: -0.02, recoilVertical: -0.005, damage: 0, spreadAds: -0.005 },
  },
  suppressor: {
    id: "suppressor",
    itemId: "suppressor",
    name: "Suppressor",
    slot: "muzzle",
    modifiers: { audibleRadius: -0.6, damageFalloffEnd: -0.15, damage: 0 },
  },
  extended_mag: {
    id: "extended_mag",
    itemId: "extended_mag",
    name: "Extended Magazine",
    slot: "magazine",
    modifiers: { magazineSize: 10, reloadTime: 0.3 },
  },
  vertical_grip: {
    id: "vertical_grip",
    itemId: "vertical_grip",
    name: "Vertical Grip",
    slot: "grip",
    modifiers: { recoilHorizontal: -0.006 },
  },
  red_dot: {
    id: "red_dot",
    itemId: "red_dot",
    name: "Red Dot Sight",
    slot: "optic",
    modifiers: { spreadAds: -0.003, adsZoom: 0.1 },
  },
};

export function getWeapon(id: string): WeaponDef | undefined {
  return WEAPONS[id];
}

export function getAttachment(id: string): AttachmentDef | undefined {
  return ATTACHMENTS[id];
}
